sonar.projectKey=SIPSE-Inspector
sonar.projectName=SIPSE Inspector
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.verbose=true
sonar.host.url=http://localhost:9000